### ISSUE TITLE
크롬스토어 링크에 오류가 생겼습니다

### ISSUE THREAD

**Issue by RUM1CUB3** [khk4912/Chzzk-PIP#1]
프로그램 재설치 하려고 연결된 링크로 들어갔는데 뭔가 이상한지 계속 없는 사이크라 나오네요
아침까지는 이러지 않았던 거 같은데 업데이트 이후로 이상해졌습니다 혹시 해결 가능하실까요

**Comment by khk4912** [comment]
현재 심사과정 중 문제로 크롬 스토어에서 내려진 상태입니다. 추후 재업로드 되면 링크 수정하도록 하겠습니다. 감사합니다.
