### ISSUE TITLE
VP80으로 녹화된 스트림의 MP4 변환 불가

### ISSUE THREAD

**Issue by emptycan1010** [khk4912/Chzzk-PIP#2]
![image](https://github.com/khk4912/Chzzk-PIP/assets/85441644/da807528-2716-4b1a-bf12-4d6b348fa0ca)
[풍월량월풍월량_5.652s.webm](https://github.com/khk4912/Chzzk-PIP/assets/85441644/78b09676-8dae-4be0-8d92-dca6aeacc162)

정상적으로 디코딩되는 파일
H264 + Opus

![image](https://github.com/khk4912/Chzzk-PIP/assets/85441644/a5cd59e2-4c72-4879-8450-3af5e20e9c96)
[따효니 DDaHyoNi_25.315s.webm](https://github.com/khk4912/Chzzk-PIP/assets/85441644/93758fdb-d9ca-4892-980a-182c91261c18)

디코딩되지 않는 파일
VP80 + Opus

동일한 방송인의 스트림 녹화시에 Chrome 121.0.6167.185 버전, Chzzk-PIP버전 0.0.20, 윈도우 11, i5 1135G7 에서 H264로 정상적으로 디코딩되는 H264 스트림으로 녹화됨

**Comment by emptycan1010** [comment]
https://github.com/emptycan1010/Chzzk-PIP/blob/ee1a062a1da463803979ac700beb21b418f5eea6/src/scripts/utils/record/record_stream.ts#L10
const mimeType = 'video/webm;codecs=vp8'; vp8으로 강제시 변환이 작동되지 않습니다. avc1으로 강제시 작동합니다.

**Comment by emptycan1010** [comment]
#3

**Comment by khk4912** [comment]
0.0.21 버전부터 AVC1 코덱으로 녹화하도록 mimeType을 수정했습니다. 감사합니다.
