### ISSUE TITLE
영상 다시보기에서 방향키 비활성화 제안

### ISSUE THREAD

**Issue by emptycan1010** [khk4912/Chzzk-PIP#5]
다시보기 시청시 방향키로 이전으로 돌아가려 할시 확장 뒤로가기랑 중첩되어 로딩된곳 이전으로 돌아가질 않습니다

**Comment by khk4912** [comment]
v0.0.23부터 방향키 탐색 기능이 다시보기에서 동작하지 않습니다. 기능 제안 감사드립니다.
