### ISSUE TITLE
파이어폭스쪽 Chzzk-PIP에 대하여

### ISSUE THREAD

**Issue by sharow0247** [khk4912/Chzzk-PIP#6]
거두절미하고 내용부터 말씀드리자면
두 항목 다 크롬쪽과 비교하여 버그로 예상되는 내용입니다

1. 녹화 활성화 시 녹화되는 영상에서는 정상적으로 음성이 녹음되나 
재생되고 있는 실시간 영상 또는 다시보기 영상이 음소거 되며 (음성 미출력)
녹화 중지 후에도 페이지 새로고침 이외의 방법으로는 복구가 되지 않음
이 경우 녹화된 파일로 정상적인 음성 확인 가능함

2. PIP 모드를 클릭하여도 활성화되지 않음

스크린샷의 기능에서는 문제 없는것 같고,
다른 기능은 사용해본 적이 없어서 말씀드릴 수 없습니다.

언제나 개발하시느라 고생하십니다.
좋은 확장프로그램을 만들어주셔서 감사합니다

추가 수정 = 파이어폭스 124.0.2 (64-비트) 사용 중이며,
다른 모든 확장프로그램 비활성 및 컴퓨터 재부팅 후 테스트를 해보았으나 해결되지 않았습니다.

**Comment by khk4912** [comment]
> 1. 녹화 활성화 시 녹화되는 영상에서는 정상적으로 음성이 녹음되나 
재생되고 있는 실시간 영상 또는 다시보기 영상이 음소거 되며 (음성 미출력)
녹화 중지 후에도 페이지 새로고침 이외의 방법으로는 복구가 되지 않음
이 경우 녹화된 파일로 정상적인 음성 확인 가능함


해당 문제는 Firefox의 MediaRecorder 구현의 버그로 보여집니다. ([#](https://bugzilla.mozilla.org/show_bug.cgi?id=1178751)) 해당 문제 해결을 위한 임시 해결책을 적용했습니다.


> 2. PIP 모드를 클릭하여도 활성화되지 않음

Firefox는 주요 브라우저 중 유일하게 Web API에서 PIP 활성화를 지원하지 않는 브라우저 입니다. ([#](https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/requestPictureInPicture#browser_compatibility))
따라서 현재로서는 PIP 버튼을 추가하는 기능 구현이 어려울 것으로 보입니다.


Firefox가 제가 주로 사용하는 브라우저가 아니기도 하고, 현재 제가 병역을 이행 중이라 Firefox 버전에 충분한 신경을 쓰지 못하고 있는 점에 사과드립니다. 
감사합니다.
